name: Drupal Coding Standards and Testing

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - dev
      - feature/**

  schedule:
    # Run At 03:30 on day-of-month 12 UTC
    - cron: '30 03 12 * *'

  workflow_dispatch:
    inputs:
      coreprurl:
        description: (optional) Core PR URL
        required: false

env:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: sqlite://tmp/test.sqlite
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  BROWSERTEST_OUTPUT_DIRECTORY: "sites/simpletest/browser_output"
  BROWSERTEST_OUTPUT_BASE_URL: ""
  MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", { "chromeOptions": { "w3c": false } }, "http://127.0.0.1:9515/wd/hub"]'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.1']
        composer-channel: ['stable']

    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-versions }}"
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv, opcache, imagick

      - name: Update composer
        run: composer --verbose self-update --${{ matrix.composer-channel }}

      - name: Dump composer version
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        run: composer --verbose install

      - run: ./vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/test.sqlite

      - run: ./vendor/bin/drush runserver $SIMPLETEST_BASE_URL &

      - run: until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null

      - name: Run a single unit test to verfiy the testing setup.
        run: ./vendor/bin/phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php

      - run: ./vendor/bin/drush
